### PR TITLE
Angular UI init

### PR DESCRIPTION
**Pull request by ljoonal**
Adds a basic foundation for the UI using Angular and Angular Material, which will help with getting the MVP shipped out quick using the preexisting components,
Fully featured with linting (including prettier & typescript & angular checks), testing (via karma, which runs the tests in a real browser), and other misc developer experience goodies.

### CODE REVIEW

**Review by andesyv — APPROVED** [review]
Awesome work! I don't know much about Angular, but to me it looks pretty neat.

However, I cannot agree with the decision to include the yarn cache in the Git history. I can see some benefits in that it could possibly be quicker to download the whole project directly from GitHub for quickly building the latest branch or the benefit of not having to download stuff via a second `yarn install` command. But the project is already very slow to clone due to the cache size and as packages change it's only gonna become progressively worse. Furthermore, since the whole git history is downloaded on each `git clone`, downloading the project this way will likely end up being slower in the future compared to cloning it and then installing only the *current* packages with `yarn install`.
My suggestion would be to "cherry-pick" away the cache from the Git history and force push the branch again after this PR has been merged while it's still straight-forward to do so.

**Comment by ljoonal** [comment]
The yarn cache is included as per Yarn V2's [Zero-Installs](https://yarnpkg.com/features/zero-installs). IMO the tradeoff is way worth it, since you're still going to need to pay the time to download the dependencies, and with 0installs it's at least just as fast (I'd say faster) than if you had to manually run `yarn install` and wait for the packages to be retrieved. Cloning the repository but not having the dependencies in it is not really an use case that I see any need to support.

The yarn docs have [a whole section about dealing with the repository size even](https://yarnpkg.com/features/zero-installs#what-does-this-do-to-my-repository-size).

**Comment by ljoonal** [comment]
To note, a challenge with using standard web technologies is translating the rust native types to TypeScript. It basically requires all the transitive types to implement the specific derive macro, which isn't really such a realistic thing to implement, and in addition we'll still lose all the nice rust trait implementations. It can be avoided by using a rust WebAssembly library, like [`yew`](https://yew.rs/) for example, like I've done in [`app_rs`](https://github.com/onlivfe/app_rs). Though to note, those libraries aren't nearly as polished or quick to work with than a preexisting JS framework like Angular with Angular Material. I'm of the opinion that both methods should be attempted, and we'll see which one makes more sense.

**Comment by Slime-Senpai** [comment]
Nice starter stuff, really forcing me to work huh

**Pull request merged**
